travis:
  secure:
    BINSTAR_TOKEN: fO14rtDGg5XP2PcOWefxy0D2uuMCOvNBPeOjmlCfB5YgBCDMJKdiYUmNWltrcVjkj+r0t9/INPVGCCRO9mD19zrs9nqjRk0sKxsgUHsj+aPFe7HanpQx31T9MxeAWKpqVk9h3wlro/6GL2d311DBNpd0zYOLcfQWAYvXF5Jz91xH4a3HcL+8IveO/1uAyqKtuaoCmHj1gGkDnw6oMn5BBdlGgfGLXwSdcm+ATz6lsIbe3GLP+0OpRFqa4jVZZ9ue4M4ZY27P7cgZcifIAdce0UTu3Pk3Fh88W0d1UTKZA7hnVvNG7m/Y1D93MjhnL4jIIpa+MzKJh7m7ZvdPYT0MLRJmgMkjLGGrY5+mTtjcRBv9rUMqxCgdKduTeaWxhuCnger6tyvcjfBc6zpf8hgL9pw290LiBXzYadIK86Nso1P1QzXMgBzwU2NoSsrohWqU4rm/t5N9yG/9tcdlXrNMQ8jY/BNzkywzfyruGpJ4zXaz47to3WgQf5wF0h/Dax53HMrVAxsRAbUw79RcC/EFRnK3jqnSlQ8tg3PyX7iyj8bNS0Uohws+Q3qiNatFYTEnR0nbFZJTt+oXwddpBQ+rNfvlwuvhvJ1HoJk77ExQYaOyYmJZDihqw7xscw2Qllt9Jh3+jB5eADfG7cj1Zo/VBRfvnPSzeSF+WsN3kGETjOk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
